### ISSUE TITLE
Cannot find module 'discord-player'

### ISSUE THREAD

**Issue by supertrio17** [Gotowka/mydbm#2]
like the title says, when I start my bot, this pops up: Cannot find module 'discord-player'

**Comment by Gotowka** [comment]
Use command `npm i discord-player@5.2.2`

**Comment by supertrio17** [comment]
Yeah, I did, but now i get this when I try to play music on it
`Bot is ready!
D:\Projekti\DBM\Sempl Tekst\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:94
    if (this.deferred || this.replied) throw new Error('INTERACTION_ALREADY_REPLIED');
                                             ^

Error [INTERACTION_ALREADY_REPLIED]: The reply to this interaction has already been sent or deferred.
    at CommandInteraction.reply (D:\Projekti\DBM\Sempl Tekst\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:94:46)
    at D:\Projekti\DBM\Sempl Tekst\actions\play_all.js:145:28 {
  [Symbol(code)]: 'INTERACTION_ALREADY_REPLIED'
}

Node.js v17.4.0`

**Comment by supertrio17** [comment]
This is how my command looks

`{
  "name": "play",
  "permissions": "NONE",
  "permissions2": "NONE",
  "restriction": "1",
  "_id": "GqscF",
  "actions": [
    {
      "member": "1",
      "varName": "",
      "info": "4",
      "varName2": "",
      "iftrue": "3",
      "iftrueVal": "2",
      "iffalse": "0",
      "iffalseVal": "",
      "name": "Check If Member"
    },
    {
      "channel": "0",
      "varName": "",
      "message": "${member}, retarde, da bih pustio pesmu moraš da budeš u kanalu!",
      "buttons": [],
      "selectMenus": [],
      "attachments": [],
      "embeds": [],
      "reply": true,
      "ephemeral": false,
      "tts": false,
      "overwrite": false,
      "dontSend": false,
      "editMessage": "0",
      "editMessageVarName": "",
      "storage": "0",
      "varName2": "",
      "name": "Send Message"
    },
    {
      "name": "End Action Sequence"
    },
    {
      "channel": "0",
      "varName": "",
      "name": "Join Voice Channel"
    },
    {
      "url": "${slashParams(\"search\")}",
      "type": "1",
      "name": "Play Music"
    },
    {
      "channel": "0",
      "varName": "",
      "message": "Pušteno!",
      "buttons": [],
      "selectMenus": [],
      "attachments": [],
      "embeds": [],
      "reply": true,
      "ephemeral": false,
      "tts": false,
      "overwrite": false,
      "dontSend": false,
      "editMessage": "0",
      "editMessageVarName": "",
      "storage": "0",
      "varName2": "",
      "name": "Send Message"
    }
  ],
  "comType": "4",
  "description": "Pusti muziku sa jutjuba",
  "parameters": [
    {
      "name": "search",
      "description": "Tekst ili url",
      "type": "STRING",
      "required": true,
      "choices": null
    }
  ]
}`

**Comment by Gotowka** [comment]
I change the action code in a moment and then it will work.

**Comment by Gotowka** [comment]
You can now update the action
