### ISSUE TITLE
Error while trying to play music!

### ISSUE THREAD

**Issue by supertrio17** [Gotowka/mydbm#3]
I get this error after using play command

`Bot is ready!
Error: Cannot destroy VoiceConnection - it has already been destroyed
    at G.destroy (D:\Projekti\DBM\Sempl Tekst\node_modules\@discordjs\voice\dist\index.js:8:10564)
    at VoiceUtils.<anonymous> (D:\Projekti\DBM\Sempl Tekst\node_modules\discord-player\dist\VoiceInterface\VoiceUtils.js:59:22)
    at Generator.throw (<anonymous>)
    at rejected (D:\Projekti\DBM\Sempl Tekst\node_modules\tslib\tslib.js:165:69)
Error with the Command "play" - Action #3 (Send Message):
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (D:\Projekti\DBM\Sempl Tekst\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (D:\Projekti\DBM\Sempl Tekst\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply (D:\Projekti\DBM\Sempl Tekst\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:103:5)
<ref *1> Queue {
  tracks: [],
  previousTracks: [
    Track {
      id: '1084621025490108417',
      title: 'Destination: Bright Blue Station',
      author: 'Sample Text - Topic',
      url: 'https://www.youtube.com/watch?v=yjh2-ZvKnYM',
      thumbnail: 'https://i3.ytimg.com/vi/yjh2-ZvKnYM/maxresdefault.jpg',
      duration: '3:08',
      views: 444,
      requestedBy: [User],
      playlist: undefined
    }
  ],
  playing: false,
  metadata: undefined,
  repeatMode: 0,
  id: '1084620937543942144',
  _streamTime: 0,
  _cooldownsTimeout: Collection(0) [Map] {},
  _activeFilters: [],
  _filtersUpdate: undefined,
  onBeforeCreateStream: null,
  player: Player {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    options: {
      autoRegisterExtractor: true,
      ytdlOptions: [Object],
      connectionTimeout: 20000
    },
    queues: Collection(1) [Map] { '670029082943160323' => [Circular *1] },
    voiceUtils: VoiceUtils { cache: [Collection [Map]] },
    extractors: Collection(0) [Map] {},
    requiredEvents: [ 'error', 'connectionError' ],
    client: Client {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      options: [Object],
      rest: [RESTManager],
      _cleanups: [Set],
      _finalizers: FinalizationRegistry {},
      ws: [WebSocketManager],
      actions: [ActionsManager],
      voice: [ClientVoiceManager],
      shard: null,
      users: UserManager {},
      guilds: GuildManager {},
      channels: ChannelManager {},
      sweepers: [Sweepers],
      presence: [ClientPresence],
      user: null,
      application: null,
      readyAt: null,
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false
  },
  guild: <ref *2> Guild {
    id: '670029082943160323',
    name: 'Ａｅｓｔｈｅｔｉｃ',
    icon: '54151a1bb84651fcc65a49f67a92e022',
    features: [ 'APPLICATION_COMMAND_PERMISSIONS_V2' ],
    commands: GuildApplicationCommandManager {
      permissions: [ApplicationCommandPermissionsManager],
      guild: [Circular *2]
    },
    members: GuildMemberManager { guild: [Circular *2] },
    channels: GuildChannelManager { guild: [Circular *2] },
    bans: GuildBanManager { guild: [Circular *2] },
    roles: RoleManager { guild: [Circular *2] },
    presences: PresenceManager {},
    voiceStates: VoiceStateManager { guild: [Circular *2] },
    stageInstances: StageInstanceManager { guild: [Circular *2] },
    invites: GuildInviteManager { guild: [Circular *2] },
    scheduledEvents: GuildScheduledEventManager { guild: [Circular *2] },
    available: true,
    shardId: 0,
    splash: null,
    banner: null,
    description: null,
    verificationLevel: 'MEDIUM',
    vanityURLCode: null,
    nsfwLevel: 'DEFAULT',
    premiumSubscriptionCount: 0,
    discoverySplash: null,
    memberCount: 30,
    large: false,
    premiumProgressBarEnabled: false,
    applicationId: null,
    afkTimeout: 60,
    afkChannelId: null,
    systemChannelId: null,
    premiumTier: 'NONE',
    explicitContentFilter: 'DISABLED',
    mfaLevel: 'NONE',
    joinedTimestamp: 1678488174963,
    defaultMessageNotifications: 'ALL_MESSAGES',
    systemChannelFlags: SystemChannelFlags { bitfield: 0 },
    maximumMembers: 250000,
    maximumPresences: null,
    approximateMemberCount: null,
    approximatePresenceCount: null,
    vanityURLUses: null,
    rulesChannelId: null,
    publicUpdatesChannelId: null,
    preferredLocale: 'en-US',
    ownerId: '410487191501013012',
    emojis: GuildEmojiManager { guild: [Circular *2] },
    stickers: GuildStickerManager { guild: [Circular *2] }
  },
  options: {
    leaveOnEnd: true,
    leaveOnStop: true,
    leaveOnEmpty: true,
    leaveOnEmptyCooldown: 1000,
    autoSelfDeaf: true,
    ytdlOptions: { quality: 'highestaudio', highWaterMark: 33554432 },
    initialVolume: 100,
    bufferingTimeout: 3000,
    spotifyBridge: true,
    disableVolume: false,
    volumeSmoothness: 0.08
  },
  connection: StreamDispatcher {
    _events: [Object: null prototype] {
      error: [Function (anonymous)],
      debug: [Function (anonymous)],
      start: [Function (anonymous)],
      finish: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    connectionTimeout: 20000,
    readyLock: false,
    voiceConnection: G {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      rejoinAttempts: 0,
      _state: [Object],
      joinConfig: [Object],
      packets: [Object],
      receiver: [j],
      debug: null,
      onNetworkingClose: [Function: bound onNetworkingClose],
      onNetworkingStateChange: [Function: bound onNetworkingStateChange],
      onNetworkingError: [Function: bound onNetworkingError],
      onNetworkingDebug: [Function: bound onNetworkingDebug],
      [Symbol(kCapture)]: false
    },
    audioPlayer: B {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _state: [Object],
      subscribers: [],
      behaviors: [Object],
      debug: [Function (anonymous)],
      [Symbol(kCapture)]: false
    },
    channel: VoiceChannel {
      type: 'GUILD_VOICE',
      guild: [Guild],
      guildId: '670029082943160323',
      parentId: '670029082943160325',
      permissionOverwrites: [PermissionOverwriteManager],
      messages: [MessageManager],
      id: '670029773031866370',
      name: '𝓕𝓕𝓐'   ,
      rawPosition: 0,
      rtcRegion: 'russia',
      bitrate: 64000,
      userLimit: 0,
      videoQualityMode: null,
      lastMessageId: '1055994412330668132',
      rateLimitPerUser: 0
    },
    paused: false,
    audioResource: T {
      playStream: [Encoder],
      edges: [Array],
      metadata: [Track],
      volume: [VolumeTransformer],
      encoder: [Encoder],
      audioPlayer: undefined,
      playbackDuration: 0,
      started: true,
      silencePaddingFrames: 5,
      silenceRemaining: -1
    },
    [Symbol(kCapture)]: false
  }
} AbortError: The operation was aborted
    at abortListener (node:events:968:14)
    at AbortSignal.<anonymous> (node:events:1004:47)
    at AbortSignal.[nodejs.internal.kHybridDispatch] (node:internal/event_target:647:20)
    at AbortSignal.dispatchEvent (node:internal/event_target:589:26)
    at abortSignal (node:internal/abort_controller:290:10)
    at AbortController.abort (node:internal/abort_controller:321:5)
    at Timeout.<anonymous> (D:\Projekti\DBM\Sempl Tekst\node_modules\@discordjs\voice\dist\index.js:9:64)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ABORT_ERR',
  [cause]: DOMException [AbortError]: This operation was aborted
      at AbortController.abort (node:internal/abort_controller:319:18)
      at Timeout.<anonymous> (D:\Projekti\DBM\Sempl Tekst\node_modules\@discordjs\voice\dist\index.js:9:64)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)
}
(node:15040) Warning: [DiscordPlayerWarning] Unhandled "connectionError" event! Events "error", "connectionError" must have event listeners!
(Use `node --trace-warnings ...` to show where the warning was created)`

**Comment by Gotowka** [comment]
What for version node modules you us?

**Comment by supertrio17** [comment]
+-- @discordjs/opus@0.9.0
+-- @discordjs/voice@0.8.0
+-- discord-bot-maker@ extraneous
+-- discord-player@5.2.2
+-- discord.js@13.8.0
+-- ffmpeg-static@5.1.0
+-- fs-extra@11.1.0
+-- fstorm@0.1.3
+-- jimp@0.22.7
+-- node-cron@3.0.2
+-- tweetnacl@1.0.3
+-- youtube-dl-exec@2.4.0
+-- ytdl-core@4.11.2
`-- ytsr@3.8.0

**Comment by supertrio17** [comment]
I tried using it with Store Json from WebAPI and play via url, but then i get this error:

D:\Projekti\DBM\Pink Panter Moderator>node bot.js
Bot is ready!
[ 'vO9pgvv7qgg' ]
WebAPI: JSON Data values starting from [items[0].id.videoId] stored to: [ID]
WebAPI: Using previously stored json data from the initial store json action within this command.
[ 'Medenjaci - Medena - (Audio 2006)' ]
WebAPI: JSON Data values starting from [items[0].snippet.title] stored to: [title]
WebAPI: Using previously stored json data from the initial store json action within this command.
[ 'https://i.ytimg.com/vi/vO9pgvv7qgg/hqdefault.jpg' ]
WebAPI: JSON Data values starting from [items[0].snippet.thumbnails.high.url] stored to: [thumbnails]
D:\Projekti\DBM\Pink Panter Moderator\actions\play_all.js:141
      if (!interaction.member.voice.channel) return interaction.reply("Error: You must join the voice channel!")
                       ^

TypeError: Cannot read properties of null (reading 'member')
    at Object.action [as Play Music] (D:\Projekti\DBM\Pink Panter Moderator\actions\play_all.js:141:24)
    at Object.Actions.callNextAction (D:\Projekti\DBM\Pink Panter Moderator\bot.js:1539:22)
    at storeData (D:\Projekti\DBM\Pink Panter Moderator\actions\store_json_from_webapi_MOD.js:196:19)
    at Object.action [as Store Json From WebAPI] (D:\Projekti\DBM\Pink Panter Moderator\actions\store_json_from_webapi_MOD.js:218:11)
    at Object.Actions.callNextAction (D:\Projekti\DBM\Pink Panter Moderator\bot.js:1539:22)
    at storeData (D:\Projekti\DBM\Pink Panter Moderator\actions\store_json_from_webapi_MOD.js:196:19)
    at Object.action [as Store Json From WebAPI] (D:\Projekti\DBM\Pink Panter Moderator\actions\store_json_from_webapi_MOD.js:218:11)
    at Object.Actions.callNextAction (D:\Projekti\DBM\Pink Panter Moderator\bot.js:1539:22)
    at storeData (D:\Projekti\DBM\Pink Panter Moderator\actions\store_json_from_webapi_MOD.js:196:19)
    at Object.action [as Store Json From WebAPI] (D:\Projekti\DBM\Pink Panter Moderator\actions\store_json_from_webapi_MOD.js:252:13)

**Comment by supertrio17** [comment]
And this happens when trying to play via spotify

D:\Projekti\DBM\Pink Panter Moderator>node bot.js
Bot is ready!
Error: Cannot destroy VoiceConnection - it has already been destroyed
    at G.destroy (D:\Projekti\DBM\Pink Panter Moderator\node_modules\discord-player\node_modules\@discordjs\voice\dist\index.js:8:10564)
    at VoiceUtils.<anonymous> (D:\Projekti\DBM\Pink Panter Moderator\node_modules\discord-player\dist\VoiceInterface\VoiceUtils.js:59:22)
    at Generator.throw (<anonymous>)
    at rejected (D:\Projekti\DBM\Pink Panter Moderator\node_modules\tslib\tslib.js:165:69)
D:\Projekti\DBM\Pink Panter Moderator\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:94
    if (this.deferred || this.replied) throw new Error('INTERACTION_ALREADY_REPLIED');
                                             ^

Error [INTERACTION_ALREADY_REPLIED]: The reply to this interaction has already been sent or deferred.
    at CommandInteraction.reply (D:\Projekti\DBM\Pink Panter Moderator\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:94:46)
    at Object.action [as Play Music] (D:\Projekti\DBM\Pink Panter Moderator\actions\play_all.js:177:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'INTERACTION_ALREADY_REPLIED'
}

Node.js v17.4.0

**Comment by supertrio17** [comment]
Now a weird thing I found out, when I put manually a link, it plays it for about 5 seconds, than it stops with no errors, but when I try to do it with temp and slash variable, then it doesnt work

**Comment by Gotowka** [comment]
Go to the file package-lock.json
and look for this: "node_modules/discord-player"
and for peerDependencies ytdl-core change to: https://github.com/matteopolak/node-ytdl-core.git#d6b56cd67aaa38c22966b98f7b36ad3db4c90192

and change for "node_modules/ytdl-core"
      ```"version": "4.11.2",
      "resolved": "git+ssh://git@github.com/matteopolak/node-ytdl-core.git#d6b56cd67aaa38c22966b98f7b36ad3db4c90192",
      "integrity": "sha512-D939t9b4ZzP3v0zDvehR2q+KgG97UTgrTKju3pOPGQcXtl4W6W5z0EpznzcJFu+OOpl7S7Ge8hv8zU65QnxYug==",
      "dependencies": {
        "m3u8stream": "^0.8.6",
        "miniget": "^4.2.2",
        "sax": "^1.1.3"
      },
      "engines": {
        "node": ">=12"
      }```

and change for "ytdl-core"
change it to this:
      ```"version": "git+ssh://git@github.com/matteopolak/node-ytdl-core.git#d6b56cd67aaa38c22966b98f7b36ad3db4c90192",
      "integrity": "sha512-D939t9b4ZzP3v0zDvehR2q+KgG97UTgrTKju3pOPGQcXtl4W6W5z0EpznzcJFu+OOpl7S7Ge8hv8zU65QnxYug==",
      "from": "ytdl-core@^4.11.2",
      "requires": {
        "m3u8stream": "^0.8.6",
        "miniget": "^4.2.2",
        "sax": "^1.1.3"
      }```

**Comment by supertrio17** [comment]
now i get this

node:internal/errors:868
  const err = new Error(message);
              ^

Error: Command failed: npm i chalk
npm ERR! Invalid Version: git+ssh://git@github.com/matteopolak/node-ytdl-core.git#d6b56cd67aaa38c22966b98f7b36ad3db4c90192

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SavoX\AppData\Local\npm-cache\_logs\2023-03-15T16_31_31_546Z-debug-0.log

    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at D:\Projekti\DBM\Pink Panter Moderator\actions\aaa_dbmmods_dependencies_MOD.js:6:32
    at new Promise (<anonymous>)
    at Object.installModule (D:\Projekti\DBM\Pink Panter Moderator\actions\aaa_dbmmods_dependencies_MOD.js:5:12)
    at Object.require (D:\Projekti\DBM\Pink Panter Moderator\actions\aaa_dbmmods_dependencies_MOD.js:19:12)
    at Object.mod (D:\Projekti\DBM\Pink Panter Moderator\actions\canvas_create_image_MOD.js:101:41)
    at D:\Projekti\DBM\Pink Panter Moderator\bot.js:1340:19
    at Array.forEach (<anonymous>) {
  status: 1,
  signal: null,
  output: [
    null,
    Buffer(0) [Uint8Array] [],
    Buffer(272) [Uint8Array] [
      110, 112, 109,  32,  69,  82,  82,  33,  32,  73, 110, 118,
       97, 108, 105, 100,  32,  86, 101, 114, 115, 105, 111, 110,
       58,  32, 103, 105, 116,  43, 115, 115, 104,  58,  47,  47,
      103, 105, 116,  64, 103, 105, 116, 104, 117,  98,  46,  99,
      111, 109,  47, 109,  97, 116, 116, 101, 111, 112, 111, 108,
       97, 107,  47, 110, 111, 100, 101,  45, 121, 116, 100, 108,
       45,  99, 111, 114, 101,  46, 103, 105, 116,  35, 100,  54,
       98,  53,  54,  99, 100,  54,  55,  97,  97,  97,  51,  56,
       99,  50,  50,  57,
      ... 172 more items
    ]
  ],
  pid: 21148,
  stdout: Buffer(0) [Uint8Array] [],
  stderr: Buffer(272) [Uint8Array] [
    110, 112, 109,  32,  69,  82,  82,  33,  32,  73, 110, 118,
     97, 108, 105, 100,  32,  86, 101, 114, 115, 105, 111, 110,
     58,  32, 103, 105, 116,  43, 115, 115, 104,  58,  47,  47,
    103, 105, 116,  64, 103, 105, 116, 104, 117,  98,  46,  99,
    111, 109,  47, 109,  97, 116, 116, 101, 111, 112, 111, 108,
     97, 107,  47, 110, 111, 100, 101,  45, 121, 116, 100, 108,
     45,  99, 111, 114, 101,  46, 103, 105, 116,  35, 100,  54,
     98,  53,  54,  99, 100,  54,  55,  97,  97,  97,  51,  56,
     99,  50,  50,  57,
    ... 172 more items
  ]
}

Node.js v18.13.0

**Comment by supertrio17** [comment]
I undid changes to package-lock.json and got message to work, but music still wont play

Bot is ready!
Error: Cannot destroy VoiceConnection - it has already been destroyed
    at G.destroy (D:\Projekti\DBM\Pink Panter Moderator\node_modules\@discordjs\voice\dist\index.js:8:10564)
    at VoiceUtils.<anonymous> (D:\Projekti\DBM\Pink Panter Moderator\node_modules\discord-player\dist\VoiceInterface\VoiceUtils.js:59:22)
    at Generator.throw (<anonymous>)
    at rejected (D:\Projekti\DBM\Pink Panter Moderator\node_modules\tslib\tslib.js:165:69)
Error with the Command "play":
DiscordAPIError: Unknown interaction
    at RequestHandler.execute (D:\Projekti\DBM\Pink Panter Moderator\node_modules\discord.js\src\rest\RequestHandler.js:350:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RequestHandler.push (D:\Projekti\DBM\Pink Panter Moderator\node_modules\discord.js\src\rest\RequestHandler.js:51:14)
    at async CommandInteraction.reply (D:\Projekti\DBM\Pink Panter Moderator\node_modules\discord.js\src\structures\interfaces\InteractionResponses.js:103:5)
<ref *1> Queue {
  tracks: [],
  previousTracks: [
    Track {
      id: '1085604948156219393',
      title: 'Medenjaci - Medena - (Audio 2006)',
      author: 'Grand Production',
      url: 'https://www.youtube.com/watch?v=vO9pgvv7qgg',
      thumbnail: 'https://i3.ytimg.com/vi/vO9pgvv7qgg/maxresdefault.jpg',
      duration: '3:59',
      views: 2501110,
      requestedBy: [User],
      playlist: undefined
    }
  ],
  playing: false,
  metadata: undefined,
  repeatMode: 0,
  id: '1085604858792378368',
  _streamTime: 0,
  _cooldownsTimeout: Collection(0) [Map] {},
  _activeFilters: [],
  _filtersUpdate: undefined,
  onBeforeCreateStream: null,
  player: Player {
    _events: [Object: null prototype] {},
    _eventsCount: 0,
    _maxListeners: undefined,
    options: {
      autoRegisterExtractor: true,
      ytdlOptions: [Object],
      connectionTimeout: 20000
    },
    queues: Collection(1) [Map] { '1083049125920133200' => [Circular *1] },
    voiceUtils: VoiceUtils { cache: [Collection [Map]] },
    extractors: Collection(0) [Map] {},
    requiredEvents: [ 'error', 'connectionError' ],
    client: Client {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      options: [Object],
      rest: [RESTManager],
      _cleanups: [Set],
      _finalizers: FinalizationRegistry {},
      ws: [WebSocketManager],
      actions: [ActionsManager],
      voice: [ClientVoiceManager],
      shard: null,
      users: UserManager {},
      guilds: GuildManager {},
      channels: ChannelManager {},
      sweepers: [Sweepers],
      presence: [ClientPresence],
      user: null,
      application: null,
      readyAt: null,
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false
  },
  guild: <ref *2> Guild {
    id: '1083049125920133200',
    name: 'Pink Panteri',
    icon: '2467419305c05d72eb077933d94d4716',
    features: [],
    commands: GuildApplicationCommandManager {
      permissions: [ApplicationCommandPermissionsManager],
      guild: [Circular *2]
    },
    members: GuildMemberManager { guild: [Circular *2] },
    channels: GuildChannelManager { guild: [Circular *2] },
    bans: GuildBanManager { guild: [Circular *2] },
    roles: RoleManager { guild: [Circular *2] },
    presences: PresenceManager {},
    voiceStates: VoiceStateManager { guild: [Circular *2] },
    stageInstances: StageInstanceManager { guild: [Circular *2] },
    invites: GuildInviteManager { guild: [Circular *2] },
    scheduledEvents: GuildScheduledEventManager { guild: [Circular *2] },
    available: true,
    shardId: 0,
    splash: null,
    banner: null,
    description: null,
    verificationLevel: 'NONE',
    vanityURLCode: null,
    nsfwLevel: 'DEFAULT',
    premiumSubscriptionCount: 0,
    discoverySplash: null,
    memberCount: 10,
    large: false,
    premiumProgressBarEnabled: false,
    applicationId: null,
    afkTimeout: 1800,
    afkChannelId: '1083233919027122247',
    systemChannelId: '1083049126368919702',
    premiumTier: 'NONE',
    explicitContentFilter: 'DISABLED',
    mfaLevel: 'NONE',
    joinedTimestamp: 1678333981031,
    defaultMessageNotifications: 'ALL_MESSAGES',
    systemChannelFlags: SystemChannelFlags { bitfield: 15 },
    maximumMembers: 500000,
    maximumPresences: null,
    approximateMemberCount: null,
    approximatePresenceCount: null,
    vanityURLUses: null,
    rulesChannelId: null,
    publicUpdatesChannelId: null,
    preferredLocale: 'en-US',
    ownerId: '266492206846574612',
    emojis: GuildEmojiManager { guild: [Circular *2] },
    stickers: GuildStickerManager { guild: [Circular *2] }
  },
  options: {
    leaveOnEnd: true,
    leaveOnStop: true,
    leaveOnEmpty: true,
    leaveOnEmptyCooldown: 1000,
    autoSelfDeaf: true,
    ytdlOptions: { quality: 'highestaudio', highWaterMark: 33554432 },
    initialVolume: 100,
    bufferingTimeout: 3000,
    spotifyBridge: true,
    disableVolume: false,
    volumeSmoothness: 0.08
  },
  connection: StreamDispatcher {
    _events: [Object: null prototype] {
      error: [Function (anonymous)],
      debug: [Function (anonymous)],
      start: [Function (anonymous)],
      finish: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    connectionTimeout: 20000,
    readyLock: false,
    voiceConnection: G {
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      rejoinAttempts: 0,
      _state: [Object],
      joinConfig: [Object],
      packets: [Object],
      receiver: [j],
      debug: null,
      onNetworkingClose: [Function: bound onNetworkingClose],
      onNetworkingStateChange: [Function: bound onNetworkingStateChange],
      onNetworkingError: [Function: bound onNetworkingError],
      onNetworkingDebug: [Function: bound onNetworkingDebug],
      [Symbol(kCapture)]: false
    },
    audioPlayer: B {
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _state: [Object],
      subscribers: [],
      behaviors: [Object],
      debug: [Function (anonymous)],
      [Symbol(kCapture)]: false
    },
    channel: VoiceChannel {
      type: 'GUILD_VOICE',
      guild: [Guild],
      guildId: '1083049125920133200',
      parentId: '1083049126368919706',
      permissionOverwrites: [PermissionOverwriteManager],
      id: '1083049126368919709',
      name: '𝕃𝕠𝕓𝕓𝕪 #𝟙'      ,
      rawPosition: 0,
      rtcRegion: null,
      bitrate: 64000,
      userLimit: 5,
      videoQualityMode: null
    },
    paused: false,
    audioResource: T {
      playStream: [Encoder],
      edges: [Array],
      metadata: [Track],
      volume: [VolumeTransformer],
      encoder: [Encoder],
      audioPlayer: undefined,
      playbackDuration: 0,
      started: true,
      silencePaddingFrames: 5,
      silenceRemaining: -1
    },
    [Symbol(kCapture)]: false
  }
} AbortError: The operation was aborted
    at EventTarget.abortListener (node:events:958:14)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:735:20)
    at EventTarget.dispatchEvent (node:internal/event_target:677:26)
    at abortSignal (node:internal/abort_controller:308:10)
    at AbortController.abort (node:internal/abort_controller:338:5)
    at Timeout.<anonymous> (D:\Projekti\DBM\Pink Panter Moderator\node_modules\@discordjs\voice\dist\index.js:9:64)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) {
  code: 'ABORT_ERR',
  [cause]: DOMException [AbortError]: This operation was aborted
      at new DOMException (node:internal/per_context/domexception:53:5)
      at AbortController.abort (node:internal/abort_controller:336:18)
      at Timeout.<anonymous> (D:\Projekti\DBM\Pink Panter Moderator\node_modules\@discordjs\voice\dist\index.js:9:64)
      at listOnTimeout (node:internal/timers:564:17)
      at process.processTimers (node:internal/timers:507:7)
}
(node:20612) Warning: [DiscordPlayerWarning] Unhandled "connectionError" event! Events "error", "connectionError" must have event listeners!
(Use `node --trace-warnings ...` to show where the warning was created)

![image](https://user-images.githubusercontent.com/57882120/225381463-6cd2a7f9-b832-44ab-9b8d-bac41c61f337.png)

**Comment by supertrio17** [comment]
Started working by some weird magic!
